import type { Metadata } from "next";
import Link from "next/link";
import { ComparePokemon } from "@/components/tools/ComparePokemon";
import { JsonLd } from "@/components/content/JsonLd";
import { getPokemonBySlug } from "@/lib/pokemon-catalog";
import { breadcrumbSchema, organizationSchema, webApplicationSchema } from "@/lib/seo";
import type { PokemonRecord } from "@/types/pokemon";
const path = "/compare-pokemon"; const description = "Compare 2–4 Pokémon side by side across base stats, types, generation, abilities, weaknesses, resistances, immunities, and BST.";
export const metadata: Metadata = { title: { absolute: "Compare Pokémon – Stats, Types & Matchups" }, description, alternates: { canonical: path }, openGraph: { title: "Compare Pokémon", description, url: path } };
export default function Page() {
  const initialEntries = [getPokemonBySlug("charizard"), getPokemonBySlug("dragonite")].filter((entry): entry is PokemonRecord => Boolean(entry));
  return <><JsonLd data={[organizationSchema(), webApplicationSchema("Compare Pokémon", path, description), breadcrumbSchema([["Home", "/"], ["Compare Pokémon", path]])]} /><section className="subpage-hero"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><span>Compare Pokémon</span></nav><h1>Compare <em>Pokémon</em></h1><p>Compare two to four Pokémon side by side across stats, types, abilities, and defensive matchups.</p></section><ComparePokemon initialEntries={initialEntries} /><div className="content-wrap compare-guide"><section className="content-section"><div className="content-heading"><span className="eyebrow">HOW IT WORKS</span><h2>Compare Pokémon in three steps</h2><p>The example starts with Charizard and Dragonite so the comparison is useful immediately.</p></div><div className="steps-grid"><article><span>01</span><h3>Choose 2–4 Pokémon</h3><p>Search by species name, add up to four columns, or remove the example Pokémon.</p></article><article><span>02</span><h3>Read the strongest stats</h3><p>The highest value in each base-stat row is highlighted for faster scanning.</p></article><article><span>03</span><h3>Check matchups</h3><p>Compare weaknesses, resistances, and immunities before moving to team planning.</p></article></div></section><section className="content-section split-content"><div><span className="eyebrow">WHAT THE TABLE SHOWS</span><h2>More than a base-stat comparison</h2></div><div><p>Each column includes Generation, region, abilities, six base stats, Base Stat Total, weaknesses, resistances, and immunities. Type matchups are calculated from both types for dual-type Pokémon.</p><p>Open a Pokémon name for its full Pokédex profile, or continue in the <Link className="inline-content-link" href="/team-planner">Team Planner</Link> when you want to analyze up to six Pokémon together.</p></div></section></div></>; }
